//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEVAMSİZLİK
    {
        public int ID { get; set; }
        public int OgrID { get; set; }
        public System.DateTime Devamsizlik { get; set; }
    
        public virtual TBL_OGR TBL_OGR { get; set; }
    }
}
